apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-ki-deployment
  namespace: chatapp-ki-deployment
  labels:
    app: chatapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chatapp
  template:
    metadata:
      labels:
        app: chatapp
    spec:
      containers:
        - name: chatapp-frontend
          image: rohitdarekar816/chatapp-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: "http://chatapp-backend:5001"

        - name: chatapp-backend
          image: rohitdarekar816/chatapp-backend:latest
          ports:
            - containerPort: 5001
          env:
            - name: MONGODB_URI
              value: "mongodb://root:admin@chatapp-mongo:27017/chatApp?authSource=admin&retryWrites=true&w=majority"

        - name: chatapp-mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "admin"

---
apiVersion: v1
kind: Service
metadata:
  name: chatapp-ki-service
  namespace: chatapp-ki-deployment
spec:
  selector:
    app: chatapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
